apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: newlogstdio
  namespace: istio-system
spec:
  match: source.labels["app"] == "bets"
  actions:
    - handler: newloghandler
      instances:
        - newlog