---
apiVersion: v1
kind: List
items:
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        version: v2
        app: players
      name: players-v2
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      selector:
        matchLabels:
          app: players
          stack: echo
          interface: rest
          language: golang
      template:
        metadata:
          labels:
            app: players
            version: v2
            stack: echo
            interface: rest
            language: golang
        spec:
          containers:
            - image: gcr.io/mvp-mesh-pre-testing/player:latest
              imagePullPolicy: Always
              resources:
                requests:
                  memory: "5Mi"
                  cpu: "50m"
                limits:
                  memory: "10Mi"
                  cpu: "100m"
              livenessProbe:
                httpGet:
                  path: /health
                  port: 9999
                  scheme: HTTP
                initialDelaySeconds: 1
              name: players
              ports:
                - containerPort: 9999
                  name: http
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: /health
                  port: 9999
                  scheme: HTTP
                initialDelaySeconds: 1
              securityContext:
                privileged: false